### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Papiitoo** [HavekHD/miningcore-master#1]
**To Reproduce**
1. git clone repo
2. cd miningcore-master
3.  ./build-ubuntu-20.04
4. Error message:   pool@pool:~/miningcore-master$ ./build-ubuntu-20.04.sh
Hit:1 http://hu.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://hu.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://hu.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://hu.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
--2023-04-09 21:55:54--  https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 104.214.230.139
Connecting to packages.microsoft.com (packages.microsoft.com)|104.214.230.139|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3690 (3.6K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb            100%[============================================================================>]   3.60K  --.-KB/s    in 0s

2023-04-09 21:55:54 (131 MB/s) - ‘packages-microsoft-prod.deb’ saved [3690/3690]

(Reading database ... 116349 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu20.04.1) over (1.0-ubuntu20.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu20.04.1) ...
Hit:1 http://hu.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://hu.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://hu.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://hu.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsodium-dev is already the newest version (1.0.18-1).
pkg-config is already the newest version (0.29.1-0ubuntu4).
libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libzmq5 is already the newest version (4.3.2-2ubuntu1).
build-essential is already the newest version (12.8ubuntu1.1).
cmake is already the newest version (3.16.3-1ubuntu1.20.04.1).
git is already the newest version (1:2.25.1-1ubuntu3.10).
libssl-dev is already the newest version (1.1.1f-1ubuntu2.17).
dotnet-sdk-6.0 is already the newest version (6.0.407-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Building into ../../build
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored /home/pool/miningcore-master/src/Miningcore/Miningcore.csproj (in 1.35 sec).
/home/pool/miningcore-master/src/Miningcore/Mining/PoolBase.cs(384,2): error CS1513: } expected [/home/pool/miningcore-master/src/Miningcore/Miningcore.csproj]
pool@pool:~/miningcore-master$ 

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04 server

**Comment by HavekHD** [comment]
I'll look into it.  I haven't had a chance to really test everything yet as this is a complete rebase with updated dependencies.  So most likely that could be the issue.  I will work on it some more later this week as I have about 4 different things I'm trying to get done at once.

**Comment by Papiitoo** [comment]
Tanks. I try it. I'll write about the result later, I'm not at my console anymore

**Comment by HavekHD** [comment]
No problem it's most likely because I had to change the name when I did the rebase and added PDN and I haven't had time to rebuild and update all the files.  I'm just guessing from looking at your log you posted that that seems to be the issue.  I'll flash one of my laptops later this week and see if I can get this fully functional.  Once I can get the build right I plan to start adding more coin support, but it will be a long road since everyone likes to keep things secret except a select few groups.

**Comment by Papiitoo** [comment]
The error still exists.

![image](https://user-images.githubusercontent.com/108800590/230854420-2a2265c1-5bae-4299-8abc-2486c08391fd.png)

**Comment by Papiitoo** [comment]
Apart from all that, I'm very glad that someone is developing better coin support and great respect to you!! Oliverw seems to be doing very little (or nothing) with it. I think this could be a small mistake (a parenthesis or comma somewhere). Lines 380-385 in the "PoolBase.cs" file were strange to me. But I'm not a programmer...

**Comment by HavekHD** [comment]
Most likely you're 100% right I probably left something open when I was adding things in. I was doing this at like 4am the day I first started the rebase.  I'll get it together and fixed at some point this week.  Just depends how busy I am at work.

**Comment by HavekHD** [comment]
> Apart from all that, I'm very glad that someone is developing more coin support and great respect to you!! Oliverw seems to be doing very little (or nothing) with it. I think this could be a small mistake (a parenthesis or comma somewhere). Lines 380-385 in the "PoolBase.cs" file were strange to me. But I'm not a programmer...

It should hopefully be fixed now.  I was missing a couple of things from the rebase and one was right there where you said.  I have not tested the build yet cause I am at work and do not have my Linux machine with me but I THINK, keyword think lol it should be working now.  If not I will do some more digging.  But that looked like the main issue to me.

**Comment by HavekHD** [comment]
Awesome.  Let me know if you run into anything else.

**Comment by HavekHD** [comment]
Issue solved for now after last update.
